### ISSUE TITLE
dewpoint not plotted in total - ends at around 200-250mbar

### ISSUE THREAD

**Issue by peters77** [cwebster2/pyMeteo#22]
intalled pyMeteo via pip, V 0.8.

Problem: dewpoint plot ends around 200-250mbar, see example:

![skewt](https://user-images.githubusercontent.com/8840918/51478017-778e0800-1d8a-11e9-9967-e23c34d21a90.jpg)

**Comment by cwebster2** [comment]
You can view the data that produced this sounding at http://weather.uwyo.edu/cgi-bin/sounding?region=europe&TYPE=TEXT%3ALIST&YEAR=2019&MONTH=01&FROM=2112&TO=1700&STNM=10618 (which i grab and turn into these plots).    At 218 mb and above, the data has a water vapor mixing ratio of 0 g/kg and this results in the "missing" dewpoint data on the plot.  (Further to this, the dew point temperature calculation with a 0 mixing ratio ends up trying to calculate log(0), which is why I don't plot anything there.
