### ISSUE TITLE
Missing Title and legend

### ISSUE THREAD

**Issue by wxguy** [cwebster2/pyMeteo#9]
1.  I have attached the latest skewt diagram prepared after latest commit. It is actually missing the title (either lat & lon or the location name). 
2.  There is also no legend in the diagram for the curves (temps). How does one know that red is dry bulb and green is something else?
3.  The overall diagram looks good but lot of space wasted in the margin itself. Therefore, please reduce the side, bottom and top margin if possible.
4.  My suggestion is that title can come in top, legend can come where presently hodograph text is present and hodograph text can be moved right (below most usable parcel column or 500 m mixed layer parcel).

![test](https://cloud.githubusercontent.com/assets/9054645/12059920/0c05ea5a-af8b-11e5-9a08-b044cd972e36.png)

**Comment by cwebster2** [comment]
The commit above addresses your points.  Let me know what you think and if you feel and adjustments are warranted or desired.

![skewt](https://wxster.com/static/media/skewt/skewt.png)

**Comment by wxguy** [comment]
I am not sure where the problem lies. I can only see the image similar to mine posted earlier in the previous post of your's. But in my email I received the updated, including legend, skewt graph. Anyway, uploading mine for review as I found a new bug. Look at the `wrfout` file name just above the sounding location. It should have been only the file name and not the path to file name. I am sure it is relatively little bug and can be sorted out by getting only `basename` from the path. Some observation/ suggestions are below the graph.
![test](https://cloud.githubusercontent.com/assets/9054645/12070529/1815defc-b0a0-11e5-8817-70485a36d7b2.png)
1.  I hope you agree with me that the present state of skewt graph looks more polished. 
2.  The 'Virtual Temperature' and 'Lifted Surface Virtual Temperature' are dashed lines in the skewt graph and the same is depicted as a straight line in the legend.
3.  The gap between legend and surface parcel parameter can be filled with some useful thermodynamic parameters for better utilisation of space. I had some notes on many indices and may send to you if I find it.

**Comment by wxguy** [comment]
Here is the list of indices for your reference:-
http://weather.uwyo.edu/upperair/indices.html

**Comment by cwebster2** [comment]
1. I definitely agree that the plots look better
2. I'm not yet happy with the legend in that regard. If I increase the font size it allocates more horizontal space to the line and you can more clearly see they are dashed rather than the current presentation of different lengths.  I'm going to leave the issue open until I can address that.
3. Agreed.  When I have time to dig into those (hopefully in the next few days) I'll implement them and they'll be good additions to the package.
- [X] only plot base name of filename for title
- [x] fix legend line plots
- [ ] upper air thermodynamic parameters

Thanks for the input and helping improve this package!

**Comment by cwebster2** [comment]
Moving the work for upper air stats to a new issue and closing this one.
